BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;
CREATE TABLE CIDADES (
    CIDADES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADES_NOME TEXT NOT NULL
);
INSERT INTO CIDADES (NOME)
    VALUE
    ('CAMPO GRANDE'),
    ('BLUMENAU'),
    ('FLORIANOPOLIS'),
    ('SAO PAULO');
COMMIT;
SELECT * FROM CIDADES;
