BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES;
CREATE TABLE CIDADES (
    CIDADES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADES_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS(
    PESSOA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PESSOA_NOME TEXT NOT NULL,
    PESSOA_IDADE INTEGER,
    PESSOA_CIDADE_ID INTEGER NOT NULL
);

INSERT INTO CIDADES (CIDADES_NOME)
    VALUES
    ('CAMPO GRANDE'),
    ('BLUMENAU'),
    ('FLORIANOPOLIS'),
    ('SAO PAULO');

INSERT INTO PESSOAS (PESSOA_NOME, PESSOA_IDADE, PESSOA_CIDADE_ID)
    VALUES
    ('Adriano Machado', 47, 1),
    ('Karina', 45, 5),
    ('Tarsio', 51, 2),
    ('Samir', 50, 2),
    ('Pedro', 18, 3),
    ('Maria', 22, 4),
    ('Patricia', 14, 2);

COMMIT;

SELECT * FROM CIDADES;
SELECT * FROM PESSOAS;
