BEGIN TRANSACTION;
DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CPF TEXT NOT NULL,
    NOME TEXT NOT NULL,
    IDADE INT NOT NULL,
    ENDERECO CHAR(50),
    SALARIO REAL
)
COMMIT;