-- SELECT * FROM PESSOAS;
-- SELECT * FROM CIDADES;

-- SELECT PESSOA_NOME,PESSOA_IDADE
-- FROM PESSOAS;

-- SELECT DISTINCT(PESSOA_NOME)
-- FROM PESSOAS

-- SELECT * FROM PESSOAS WHERE PESSOA_IDADE IN (14,18);

-- SELECT * FROM PESSOAS WHERE PESSOA_NOME LIKE '%Adrian%';

-- SELECT COUNT(*)
-- FROM PESSOAS;

-- SELECT PESSOA_IDADE, COUNT(PESSOA_NOME)
--  FROM PESSOAS
--  GROUP BY PESSOA_IDADE;

SELECT
    CIDADES.CIDADE_NOME,
    PESSOAS.PESSOA_NOME,
    PESSOAS.PESSOA_IDADE
FROM
    PESSOAS,CIDADES
WHERE 
    PESSOAS.PESSOA_CIDADE_ID = CIDADES.CIDADE_ID;


