BEGIN TRANSACTION;


DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_CLIENTE CHAR(40) NOT NULL,
    TELEFONE_CLIENTE INTEGER,
    CPF_CLIENTE TEXT,
    ENDERECO_CLIENTE TEXT NOT NULL,
    EMAIL_CLIENTE TEXT
);


DROP TABLE IF EXISTS ATENDENTES;
CREATE TABLE ATENDENTES (
    ID_ATENDENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_ATENDENTE CHAR(40) NOT NULL,
    ENDERECO_ATENDENTE TEXT NOT NULL,
    SALARIO_ATENDENTE REAL NOT NULL,
    EMAIL_ATENDENTE TEXT
);

DROP TABLE IF EXISTS PRATELEIRAS;
CREATE TABLE PRATELEIRAS(
    ID_PRATELEIRA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME_PRATELEIRA TEXT NOT NULL,
    LOCALIZACAO_PRATELEIRA TEXT NOT NULL
);


DROP TABLE IF EXISTS ITENS_NF;
CREATE TABLE ITENS_NF(
    ID_ITENS_NF INTEGER PRIMARY KEY AUTOINCREMENT,
    COD_ITENS_NF REAL NOT NULL,
    SEQUANCIA_ITENS_NF REAL NOT NULL,
    ID_PRODUTO REAL NOT NULL,
    VALOR_PRODUTO REAL NOT NULL,
    VALOR_TOTAL_ITENS_NF REAL NOT NULL
);

DROP TABLE IF EXISTS PRODUTO;
CREATE TABLE PRODUTO (
    ID_PRODUTO INTEGER PRIMARY KEY AUTOINCREMENT,
    CODIGO_PRODUTO INT NOT NULL,
    NOME_PRODUTO TEXT NOT NULL,
    VALOR_PRODUTO REAL NOT NULL,
    QUANTIDADES_PRODUTO REAL NOT NULL,
    ID_PRATELEIRA INT NOT NULL
);


DROP TABLE IF EXISTS NOTAS_FISCAIS;
CREATE TABLE NOTAS_FISCAIS(
    ID_NOTA_FISCAL INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTA_FISCAL REAL NOT NULL,
    COD_ITENS_NF TEXT NOT NULL,
    ID_CLIENTE TEXT NOT NULL,
    YEAR DATE,
    MONTH DATE,
    DAY DATE, 
    ID_ATENDENTE TEXT NOT NULL
);



COMMIT;
