SELECT NOME_PRATELEIRA,LOCALIZACAO_PRATELEIRA
    FROM PRATELEIRAS;

SELECT ID_PRODUTO, NOME_PRODUTO, VALOR_PRODUTO
    FROM PRODUTO ORDER BY ID_PRATELEIRA;

SELECT ID_NOTA_FISCAL, NOTA_FISCAL, COD_ITENS_NF, ID_CLIENTE, YEAR, MONTH, DAY, ID_ATENDENTE
    FROM NOTAS_FISCAIS;

SELECT NOME_CLIENTE
    FROM CLIENTES;

SELECT NOME_ATENDENTE
    FROM ATENDENTES;